object Versions {
  const val kotlinJDKVersion = "1.5.0"
  const val coreKtxVersion = "1.7.0"
  const val appCompatVersion = "1.3.1"
  const val materialVersion = "1.4.0"
  const val constraintLayoutVersion = "2.1.1"
  const val glideVersion = "4.12.0"
  const val androidSvgVersion = "1.4"
  const val lottieVersion = "4.1.0"
  const val caveRockSvgVersion: String = "1.4"

  const val androidLegacySupportVersion = "1.0.0"
  const val hiltVersion = "2.38.1"

  const val multiDexVersion = "2.0.1"
  const val googlePlayServicesVisionVersion = "17.0.2"
  const val googlePlayServicesMapVersion = "16.0.0"
  const val googlePlayServicesLocationVersion = "16.0.0"
  const val googlePlayServicesPlacesVersion = "1.1.0"
  const val googlePlayServicesSafetyNetVersion = "17.0.1"
  const val googlePlayServicesMeasurementVersion = "19.0.1"

  const val firebaseCoreVersion = "19.0.1"
  const val firebaseDataBaseVersion = "20.0.1"
  const val firebaseConfigVersion = "21.0.1"
  const val firebaseMessagingVersion = "22.0.0"
  const val firebaseInAppMessagingDisplayVersion = "20.1.1"
  const val firebaseAnalyticsVersion = "19.0.0"

  const val androidRecyclerViewVersion = "1.2.1"
  const val lifecycleExtensionsVersion = "2.2.0"
  const val javaxAnnotationVersion = "1.0"
  const val adobeMobileLibraryVersion = "4.16.0"
  const val facebookAndroidSDKVersion = "5.0.1"

  const val hyperionSimpleItemVersion = "0.1.0"
  const val hyperionVersion = "0.9.27"
  const val hyperionChuckVersion = "1.1.2"
  const val appsFlyerSDKVersion = "4.9.0"
  const val installReferrerVersion = "1.0"
  const val facebookFlipperVersion = "0.10.0"
  const val facebookSoLoaderVersion = "0.9.0"
  const val timberVersion = "4.7.1"
  const val permissionsDispatcherVersion = "4.0.0"
  const val androidViewPagerVersion = "1.0.0"
  const val fragmentKtxVersion = "1.3.6"
  const val retrofitVersion = "2.9.0"
  const val gsonVersion = "2.8.6"
  const val okhttpVersion = "3.10.0"
  const val firebaseCrashlyticsVersion = "18.2.4"
  const val androidLifeCycleKtxVersion = "2.3.1"
  const val androidXBioMetricVersion = "1.1.0"

  const val perimeterSdkVersion = "1.8.0"
  const val androidKotlinXCoRoutinesVersion = "1.5.1-native-mt"
  const val androidKotlinXCoRoutinesTestVersion = "1.3.8"
  const val grpcOkHttpVersion = "1.32.2"

  const val junitVersion = "4.12"
  const val junitExtVersion = "1.1.3"
  const val espressoCoreVersion = "3.4.0"
  const val mockitoCoreVersion = "3.9.0"
  const val testRunnerVersion = "1.1.0-alpha4"
  const val androidCoreTestingVersion = "2.1.0"
}
